In [1]:
# import libraries
import numpy as np
import matplotlib.pyplot as plt

#### Create a 2D Numpy Array

In [2]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
# Cast list to Numpy Array
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
# Show the numpy array dimensions
A.ndim

2

In [5]:
# Show the numpy array  shape
A.shape

(3, 3)

In [6]:
# Show the numpy array size
A.size

9

#### Accessing different elements of a Numpy Array

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

A:[ A[0,0], A[0,1], A[0,2],      A[1,0], A[1,1], A[1,2],    A[2,0], A[2,1], A[2,2] ]

In [7]:
# Select 23 from [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
A[1, 2]

23

In [8]:
# select 33
A[2, 2]

33

In [9]:
# Access the element on the second row and third column

A[1, 2]

23

In [10]:
# Access the element on the second row and third column
A[1][2]

23

In [11]:
# Accesss elements in first row, first col
A[0][0]

11

In [15]:
# Access the element on the first row and first and second columns
A[0, 0:2]

array([11, 12])

In [17]:
# Access the element on the first and second rows and third column
A[0:2, 2]

array([13, 23])

#### Basic Operations

In [18]:
# create numpy array x
x = np.array([[1,0],[0,1]])
x

array([[1, 0],
       [0, 1]])

In [19]:
# create numpy array y
y = np.array([[2,1],[1,2]])
y

array([[2, 1],
       [1, 2]])

In [20]:
# add x & y
z = x + y
z

array([[3, 1],
       [1, 3]])

In [21]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [22]:
z = 2 * y
z

array([[4, 2],
       [2, 4]])

Multiplication of two arrays corresponds to an element-wise product or Hadamard product. Consider matrix X and Y. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same color boxes together. The result is a new matrix that is the same size as matrix Y or X, as shown in the following figure.

In [24]:
# Create a numpy array Y
Y = np.array([[2,1],[1,2]])
Y

array([[2, 1],
       [1, 2]])

In [25]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [26]:
Z = X * Y
Z

array([[2, 0],
       [0, 2]])

We can also perform matrix multiplication with the numpy arrays A and B as follows:

First, we define matrix A and B:

In [34]:
# create a matrix A
A = np.array([[0,1,1],[1,0,1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [32]:
# create a matrix B
B = np.array([[1,1],[1,1],[-1,1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [35]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [36]:
# Calculate the sine of Z

np.sin(Z)


array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [37]:
# We use the numpy attribute T to calculate the transposed matrix
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [38]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])